#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd simulation

rm -rf 0 logs foamLog.db
rm -rf constant/polyMesh/sets
rm -f system/topoSetDict
cleanCase

cd ..

# ----------------------------------------------------------------- end-of-file
