#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cd simulation

runApplication blockMesh -dict system/blockMeshDict

# Clear and copy fields
cp -r 0.org 0

runApplication setFields

# Running application
`getApplication` | tee log.`getApplication`

cd ..
